# Generated by Django 2.2.12 on 2022-05-16 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20220510_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='detailedDescription',
            field=models.TextField(default='Test Description'),
        ),
    ]
