# Generated by Django 2.2.12 on 2022-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_counter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
