# Generated by Django 2.2.12 on 2022-06-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20220605_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='avg',
            field=models.FloatField(default=0.0),
        ),
    ]
